todo_manager/todo_list/urls.py
from django.urls import path

from . import views
from .views import (ToDoListIndexView, ToDoListView, ToDoListDoneView, ToDoDetailView, ToDoItemCreateView,
                    ToDoItemUpdateView, ToDoItemDeleteView)

app_name = 'todo_list'

urlpatterns = [
    #  path('', views.index_view, name="index"),
    #  path('', ToDoListIndexView.as_view(), name="index"),
    path('', ToDoListIndexView.as_view(), name="index"),
    path('<int:pk>/', ToDoDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', ToDoItemUpdateView.as_view(), name="update"),
    path('<int:pk>/confirm-delete/', ToDoItemDeleteView.as_view(), name="delete"),
    path('list/', ToDoListView.as_view(), name="list"),
    path('done/', ToDoListDoneView.as_view(), name="done"),
    path('create/', ToDoItemCreateView.as_view(), name="create"),

]

todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path('todo-list/', include('todo_list.urls')),
    path('admin/', admin.site.urls),
]

todo_manager/todo_list/models.py
from django.db import models
from django.urls import reverse


class ToDoItem(models.Model):

    class Meta:
        verbose_name = "ToDo Item"
        ordering = ("id", )

    def get_absolute_url(self):
        return reverse("todo_list:detail", kwargs={"pk": self.pk}, )

    title = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=False)
    done = models.BooleanField(default=False)
    archived = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todo_manager/todo_list/forms.py
from django import forms

from todo_list.models import ToDoItem


class ToDoItemCreateForm(forms.ModelForm):
    class Meta:
        model = ToDoItem
        fields = ("title", "description", )
        widgets = {"description": forms.Textarea(attrs={"cols": 40, "rows": 5}, ), }

        help_texts = {
            "description": "Some useful help texts",
        }


class ToDoItemUpdateForm(forms.ModelForm):
    class Meta(ToDoItemCreateForm.Meta):
        fields = ("title", "description", "done")

todo_manager/todo_list/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import ToDoItemCreateForm, ToDoItemUpdateForm
from .models import ToDoItem


def index_view(request: HttpRequest) -> HttpResponse:
    todo_items = ToDoItem.objects.all()
    return render(
        request=request,
        template_name="todo_list/index.html",
        context={"todo_items": todo_items}
    )


class ToDoListIndexView(ListView):
    template_name = "todo_list/index.html"
    queryset = ToDoItem.objects.all()[:3]


class ToDoListView(ListView):
    #  model = ToDoItem - видит все записи
    queryset = ToDoItem.objects.filter(archived=False)


class ToDoListDoneView(ListView):
    template_name = "todo_list/index.html"
    queryset = ToDoItem.objects.filter(done=True).all()[:2]


class ToDoDetailView(DetailView):
    #  model = ToDoItem
    queryset = ToDoItem.objects.filter(archived=False)


class ToDoItemCreateView(CreateView):
    model = ToDoItem
    form_class = ToDoItemCreateForm
    #  fields = ("title", "description",)


class ToDoItemUpdateView(UpdateView):
    model = ToDoItem
    template_name_suffix = "_update_form"
    form_class = ToDoItemUpdateForm


class ToDoItemDeleteView(DeleteView):
    model = ToDoItem
    success_url = reverse_lazy("todo_list:list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)

todo_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock title %}
  </title>
</head>
{% include "components/nav_bar.html" %}

<body>
  {% block body %}
    Base Body Block
  {% endblock body %}
  <footer>
    &copy; Django ToDo App
    {% block footer %}

    {% endblock footer %}
  </footer>
</body>
</html>

todo_manager/templates/components/nav_bar.html
<nav>
  <ul>
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'todo_list:index' %}">ToDo List</a></li>
    <li><a href="#">About</a></li>
  </ul>

</nav>

todo_manager/templates/index.html
{% extends 'base.html' %}

{% block title %}
  TODO App Index
{% endblock title %}

{% block body %}
  <h1>Welcome to our ToDo App!</h1>
  <h2>Work in progress!</h2>
  <h3>It is {% now "jS F Y H:i" %}</h3>
  <div>
    <div>
      abc
    </div>
  </div>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/base.html
{% extends 'base.html' %}

{% block footer %}
  ToDo List
{% endblock %}

todo_manager/todo_list/templates/todo_list/components/todo_items_list.html
<ul>
  {% for todo_item in object_list %}
  <li>
    <a href="{% url 'todo_list:detail' pk=todo_item.pk %}">
      {{ todo_item.title }}
      {% if todo_item.done %}
      ✅
      {% else %}
      ❌
      {% endif %}
    </a>
  </li>
  {% endfor %}
</ul>

todo_manager/todo_list/templates/todo_list/index.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo List App
{% endblock %}

{% block body %}
  <h1>ToDo List App</h1>
  <ul>
    <li><a href="{% url 'todo_list:list' %}">All ToDo Items</a></li>
    <li><a href="{% url 'todo_list:done' %}">Done ToDo Items</a></li>
    <li><a href="{% url 'todo_list:create' %}">Create ToDo Item</a></li>
  </ul>

  <h2>ToDo's:</h2>
    {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_confirm_delete.html
{% extends 'todo_list/base.html' %}

{% block title %}
  Confirm Delete ToDo Item # {{ object.id }}
{% endblock %}

{% block body %}
  <h2>Confirm delete {{ object.title }}</h2>
  <p>
    Are you sure to delete ToDo Item "{{ object.title }}" with description
    <i>{{ object.description }}</i>?
  </p>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Delete</button>
  </form>

  <div>
    <a href="{% url 'todo_list:detail' object.id %}">Back to ToDoItem details</a>
  </div>

{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_detail.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo # {{object.pk}}
{% endblock %}

{% block body %}

  <h3>ToDo:</h3>
  <div>
    <div>Title: <strong>{{ object.title }}</strong></div>
    <div>Done: <strong>{{ object.done }}</strong></div>
    <div>Description: <strong>{{ object.description }}</strong></div>
  </div>

  <ul>
    <li>
      <a href="{% url 'todo_list:update' pk=object.pk %}">Update ToDoItem</a>
    </li>
    <li>
      <a href="{% url 'todo_list:delete' pk=object.pk %}">Delete ToDoItem</a>
    </li>
  </ul>

{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_form.html
{% extends 'todo_list/base.html' %}

{% block title %}
  Create new ToDo Item
{% endblock %}

{% block body %}

  <h3>Create new ToDo:</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
  </form>

{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_list.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDo List
{% endblock %}

{% block body %}

  <h3>ToDo's:</h3>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_update_form.html
{% extends 'todo_list/base.html' %}

{% block title %}
  Update ToDo # {{ object.id }}
{% endblock %}

{% block body %}

  <h3>Update ToDo:</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
  </form>
  <div>
    <a href="{% url 'todo_list:detail' object.id %}">Back to ToDoItem details</a>
  </div>
{% endblock %}